name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Step 3: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/result:${{ github.sha }} ./result
        docker build -t ${{ secrets.DOCKER_USERNAME }}/vote:${{ github.sha }} ./vote
        docker build -t ${{ secrets.DOCKER_USERNAME }}/worker:${{ github.sha }} ./worker

    # Step 4: Push Docker image to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/result:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/vote:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/worker:${{ github.sha }}

  deploy:
    runs-on: self-hosted  # Run on your self-hosted runner
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'

    - name: Set up SSH private key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY }}" > ~/.ssh/new-kp.pem
        chmod 600 ~/.ssh/new-kp.pem  # Set appropriate permissions for the private key
        # ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
        
    - name: Deploy to EC2
      #uses: appleboy/ssh-action@v0.1.3
      #with:
        #host: ${{ secrets.EC2_HOST }}
        #username: ubuntu
        #key:  ${{ secrets.EC2_KEY }}
        #port: 22
        #debug: true # Enable debug for more detailed logs
      run: |
          ssh -i ~/.ssh/new-kp.pem ubuntu@${{ secrets.EC2_HOST }}
          sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/result:${{ github.sha }}
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/vote:${{ github.sha }}
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/worker:${{ github.sha }}
          sudo docker-compose up -d
